/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2021.11.26
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The CampaignIdScheduleBody model module.
 * @module model/CampaignIdScheduleBody
 * @version 2021.11.26
 */
export class CampaignIdScheduleBody {
  /**
   * Constructs a new <code>CampaignIdScheduleBody</code>.
   * @alias module:model/CampaignIdScheduleBody
   * @class
   * @param sendTime {String}  A timestamp of the format `%Y-%m-%d %H:%M:%S` in the UTC timezone.  Ex:  `2022-01-13 00:00:00` 
   */
  constructor(sendTime) {
    this.sendTime = sendTime;
  }

  /**
   * Constructs a <code>CampaignIdScheduleBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CampaignIdScheduleBody} obj Optional instance to populate.
   * @return {module:model/CampaignIdScheduleBody} The populated <code>CampaignIdScheduleBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CampaignIdScheduleBody();
      if (data.hasOwnProperty('send_time'))
        obj.sendTime = ApiClient.convertToType(data['send_time'], 'String');
    }
    return obj;
  }
}

/**
 *  A timestamp of the format `%Y-%m-%d %H:%M:%S` in the UTC timezone.  Ex:  `2022-01-13 00:00:00` 
 * @member {String} sendTime
 * @default '2022-01-13 00:00:00'
 */
CampaignIdScheduleBody.prototype.sendTime = '2022-01-13 00:00:00';

