/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2022.03.29
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {CheckMembershipResponseInner} from './CheckMembershipResponseInner.js';

/**
 * The CheckMembershipResponse model module.
 * @module model/CheckMembershipResponse
 * @version 2022.03.29
 */
export class CheckMembershipResponse extends Array {
  /**
   * Constructs a new <code>CheckMembershipResponse</code>.
   * @alias module:model/CheckMembershipResponse
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>CheckMembershipResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CheckMembershipResponse} obj Optional instance to populate.
   * @return {module:model/CheckMembershipResponse} The populated <code>CheckMembershipResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CheckMembershipResponse();
      ApiClient.constructFromObject(data, obj, 'CheckMembershipResponseInner');
    }
    return obj;
  }
}
