/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2021.11.26
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The DeleteEmail model module.
 * @module model/DeleteEmail
 * @version 2021.11.26
 */
export class DeleteEmail {
  /**
   * Constructs a new <code>DeleteEmail</code>.
   * @alias module:model/DeleteEmail
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeleteEmail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeleteEmail} obj Optional instance to populate.
   * @return {module:model/DeleteEmail} The populated <code>DeleteEmail</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeleteEmail();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
DeleteEmail.prototype.email = undefined;

