/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2022.03.29
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The DeletePerson model module.
 * @module model/DeletePerson
 * @version 2022.03.29
 */
export class DeletePerson {
  /**
   * Constructs a new <code>DeletePerson</code>.
   * @alias module:model/DeletePerson
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeletePerson</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeletePerson} obj Optional instance to populate.
   * @return {module:model/DeletePerson} The populated <code>DeletePerson</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeletePerson();
      if (data.hasOwnProperty('person_id'))
        obj.personId = ApiClient.convertToType(data['person_id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} personId
 */
DeletePerson.prototype.personId = undefined;

