/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2022.03.29
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The DeletePhone model module.
 * @module model/DeletePhone
 * @version 2022.03.29
 */
export class DeletePhone {
  /**
   * Constructs a new <code>DeletePhone</code>.
   * @alias module:model/DeletePhone
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeletePhone</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeletePhone} obj Optional instance to populate.
   * @return {module:model/DeletePhone} The populated <code>DeletePhone</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeletePhone();
      if (data.hasOwnProperty('phone_number'))
        obj.phoneNumber = ApiClient.convertToType(data['phone_number'], 'String');
    }
    return obj;
  }
}

/**
 * Phone Number
 * @member {String} phoneNumber
 */
DeletePhone.prototype.phoneNumber = undefined;

