/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2021.11.26
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {DeprecatedGetListResponseData} from './DeprecatedGetListResponseData.js';

/**
 * The DeprecatedGetListResponse model module.
 * @module model/DeprecatedGetListResponse
 * @version 2021.11.26
 */
export class DeprecatedGetListResponse {
  /**
   * Constructs a new <code>DeprecatedGetListResponse</code>.
   * @alias module:model/DeprecatedGetListResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeprecatedGetListResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeprecatedGetListResponse} obj Optional instance to populate.
   * @return {module:model/DeprecatedGetListResponse} The populated <code>DeprecatedGetListResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeprecatedGetListResponse();
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], 'Number');
      if (data.hasOwnProperty('end'))
        obj.end = ApiClient.convertToType(data['end'], 'Number');
      if (data.hasOwnProperty('page'))
        obj.page = ApiClient.convertToType(data['page'], 'Number');
      if (data.hasOwnProperty('size'))
        obj.size = ApiClient.convertToType(data['size'], 'Number');
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], 'Number');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [DeprecatedGetListResponseData]);
    }
    return obj;
  }
}

/**
 * @member {String} _object
 */
DeprecatedGetListResponse.prototype._object = undefined;

/**
 * @member {Number} start
 */
DeprecatedGetListResponse.prototype.start = undefined;

/**
 * @member {Number} end
 */
DeprecatedGetListResponse.prototype.end = undefined;

/**
 * @member {Number} page
 */
DeprecatedGetListResponse.prototype.page = undefined;

/**
 * @member {Number} size
 */
DeprecatedGetListResponse.prototype.size = undefined;

/**
 * @member {Number} total
 */
DeprecatedGetListResponse.prototype.total = undefined;

/**
 * @member {Array.<module:model/DeprecatedGetListResponseData>} data
 */
DeprecatedGetListResponse.prototype.data = undefined;

