/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2021.11.26
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The GlobalExclusionResponseDataData model module.
 * @module model/GlobalExclusionResponseDataData
 * @version 2021.11.26
 */
export class GlobalExclusionResponseDataData {
  /**
   * Constructs a new <code>GlobalExclusionResponseDataData</code>.
   * @alias module:model/GlobalExclusionResponseDataData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GlobalExclusionResponseDataData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GlobalExclusionResponseDataData} obj Optional instance to populate.
   * @return {module:model/GlobalExclusionResponseDataData} The populated <code>GlobalExclusionResponseDataData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GlobalExclusionResponseDataData();
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('reason'))
        obj.reason = ApiClient.convertToType(data['reason'], 'String');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} _object
 */
GlobalExclusionResponseDataData.prototype._object = undefined;

/**
 * @member {String} email
 */
GlobalExclusionResponseDataData.prototype.email = undefined;

/**
 * @member {String} reason
 */
GlobalExclusionResponseDataData.prototype.reason = undefined;

/**
 * @member {String} timestamp
 */
GlobalExclusionResponseDataData.prototype.timestamp = undefined;

