/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2021.11.26
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {IdentifyPayloadProperties} from './IdentifyPayloadProperties.js';

/**
 * The IdentifyPayload model module.
 * @module model/IdentifyPayload
 * @version 2021.11.26
 */
export class IdentifyPayload {
  /**
   * Constructs a new <code>IdentifyPayload</code>.
   * @alias module:model/IdentifyPayload
   * @class
   * @param token {String} 
   * @param properties {module:model/IdentifyPayloadProperties} 
   */
  constructor(token, properties) {
    this.token = token;
    this.properties = properties;
  }

  /**
   * Constructs a <code>IdentifyPayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdentifyPayload} obj Optional instance to populate.
   * @return {module:model/IdentifyPayload} The populated <code>IdentifyPayload</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IdentifyPayload();
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
      if (data.hasOwnProperty('properties'))
        obj.properties = IdentifyPayloadProperties.constructFromObject(data['properties']);
    }
    return obj;
  }
}

/**
 * @member {String} token
 */
IdentifyPayload.prototype.token = undefined;

/**
 * @member {module:model/IdentifyPayloadProperties} properties
 */
IdentifyPayload.prototype.properties = undefined;

