/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2022.03.29
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The IdentifyPayloadProperties model module.
 * @module model/IdentifyPayloadProperties
 * @version 2022.03.29
 */
export class IdentifyPayloadProperties {
  /**
   * Constructs a new <code>IdentifyPayloadProperties</code>.
   * @alias module:model/IdentifyPayloadProperties
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IdentifyPayloadProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdentifyPayloadProperties} obj Optional instance to populate.
   * @return {module:model/IdentifyPayloadProperties} The populated <code>IdentifyPayloadProperties</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IdentifyPayloadProperties();
      if (data.hasOwnProperty('$email'))
        obj.email = ApiClient.convertToType(data['$email'], 'String');
      if (data.hasOwnProperty('$first_name'))
        obj.firstName = ApiClient.convertToType(data['$first_name'], 'String');
      if (data.hasOwnProperty('$last_name'))
        obj.lastName = ApiClient.convertToType(data['$last_name'], 'String');
      if (data.hasOwnProperty('$phone_number'))
        obj.phoneNumber = ApiClient.convertToType(data['$phone_number'], 'String');
      if (data.hasOwnProperty('$title'))
        obj.title = ApiClient.convertToType(data['$title'], 'String');
      if (data.hasOwnProperty('$organization'))
        obj.organization = ApiClient.convertToType(data['$organization'], 'String');
      if (data.hasOwnProperty('$city'))
        obj.city = ApiClient.convertToType(data['$city'], 'String');
      if (data.hasOwnProperty('$region'))
        obj.region = ApiClient.convertToType(data['$region'], 'String');
      if (data.hasOwnProperty('$country'))
        obj.country = ApiClient.convertToType(data['$country'], 'String');
      if (data.hasOwnProperty('$zip'))
        obj.zip = ApiClient.convertToType(data['$zip'], 'String');
      if (data.hasOwnProperty('$image'))
        obj.image = ApiClient.convertToType(data['$image'], 'String');
      if (data.hasOwnProperty('$consent'))
        obj.consent = ApiClient.convertToType(data['$consent'], 'String');
      if (data.hasOwnProperty('YOUR_CUSTOM_FIELD'))
        obj.YOUR_CUSTOM_FIELD = ApiClient.convertToType(data['YOUR_CUSTOM_FIELD'], Object);
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
IdentifyPayloadProperties.prototype.email = undefined;

/**
 * @member {String} firstName
 */
IdentifyPayloadProperties.prototype.firstName = undefined;

/**
 * @member {String} lastName
 */
IdentifyPayloadProperties.prototype.lastName = undefined;

/**
 * @member {String} phoneNumber
 */
IdentifyPayloadProperties.prototype.phoneNumber = undefined;

/**
 * @member {String} title
 */
IdentifyPayloadProperties.prototype.title = undefined;

/**
 * @member {String} organization
 */
IdentifyPayloadProperties.prototype.organization = undefined;

/**
 * @member {String} city
 */
IdentifyPayloadProperties.prototype.city = undefined;

/**
 * @member {String} region
 */
IdentifyPayloadProperties.prototype.region = undefined;

/**
 * @member {String} country
 */
IdentifyPayloadProperties.prototype.country = undefined;

/**
 * @member {String} zip
 */
IdentifyPayloadProperties.prototype.zip = undefined;

/**
 * @member {String} image
 */
IdentifyPayloadProperties.prototype.image = undefined;

/**
 * @member {String} consent
 */
IdentifyPayloadProperties.prototype.consent = undefined;

/**
 * @member {Object} YOUR_CUSTOM_FIELD
 */
IdentifyPayloadProperties.prototype.YOUR_CUSTOM_FIELD = undefined;

