/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2022.03.29
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The IdentifyPayloadPost model module.
 * @module model/IdentifyPayloadPost
 * @version 2022.03.29
 */
export class IdentifyPayloadPost {
  /**
   * Constructs a new <code>IdentifyPayloadPost</code>.
   * @alias module:model/IdentifyPayloadPost
   * @class
   * @param data {String} 
   */
  constructor(data) {
    this.data = data;
  }

  /**
   * Constructs a <code>IdentifyPayloadPost</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IdentifyPayloadPost} obj Optional instance to populate.
   * @return {module:model/IdentifyPayloadPost} The populated <code>IdentifyPayloadPost</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IdentifyPayloadPost();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} data
 * @default '{"token": "PUBLIC_KEY","properties": {"$email":"ben.franklin@klaviyo.com"}}'
 */
IdentifyPayloadPost.prototype.data = '{"token": "PUBLIC_KEY","properties": {"$email":"ben.franklin@klaviyo.com"}}';

