/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2021.11.26
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The InlineResponse20012Data model module.
 * @module model/InlineResponse20012Data
 * @version 2021.11.26
 */
export class InlineResponse20012Data {
  /**
   * Constructs a new <code>InlineResponse20012Data</code>.
   * @alias module:model/InlineResponse20012Data
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse20012Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20012Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse20012Data} The populated <code>InlineResponse20012Data</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20012Data();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('customer_id'))
        obj.customerId = ApiClient.convertToType(data['customer_id'], 'String');
      if (data.hasOwnProperty('variation_id'))
        obj.variationId = ApiClient.convertToType(data['variation_id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
InlineResponse20012Data.prototype.email = undefined;

/**
 * @member {String} status
 */
InlineResponse20012Data.prototype.status = undefined;

/**
 * @member {String} customerId
 */
InlineResponse20012Data.prototype.customerId = undefined;

/**
 * @member {String} variationId
 */
InlineResponse20012Data.prototype.variationId = undefined;

