/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2022.03.29
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The ListListIdBody model module.
 * @module model/ListListIdBody
 * @version 2022.03.29
 */
export class ListListIdBody {
  /**
   * Constructs a new <code>ListListIdBody</code>.
   * @alias module:model/ListListIdBody
   * @class
   * @param listName {String} 
   */
  constructor(listName) {
    this.listName = listName;
  }

  /**
   * Constructs a <code>ListListIdBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListListIdBody} obj Optional instance to populate.
   * @return {module:model/ListListIdBody} The populated <code>ListListIdBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListListIdBody();
      if (data.hasOwnProperty('list_name'))
        obj.listName = ApiClient.convertToType(data['list_name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} listName
 * @default 'MyRenamedList'
 */
ListListIdBody.prototype.listName = 'MyRenamedList';

