/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2021.11.26
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The ListIdMembersBody1 model module.
 * @module model/ListIdMembersBody1
 * @version 2021.11.26
 */
export class ListIdMembersBody1 {
  /**
   * Constructs a new <code>ListIdMembersBody1</code>.
   *  The profiles that you would like to remove from the list.   Example:  {   \&quot;emails\&quot;:[\&quot;george.washington@klaviyo.com\&quot;,\&quot;abraham.lincoln@klaviyo.com\&quot;],   \&quot;phone_numbers\&quot;:[\&quot;+13239169023\&quot;],   \&quot;push_tokens\&quot;:[\&quot;03df25c845d460bcdad7802d2vf6fc1dfde97283bf75cc993eb6dca835ea2e2r\&quot;] } 
   * @alias module:model/ListIdMembersBody1
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ListIdMembersBody1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListIdMembersBody1} obj Optional instance to populate.
   * @return {module:model/ListIdMembersBody1} The populated <code>ListIdMembersBody1</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListIdMembersBody1();
      if (data.hasOwnProperty('emails'))
        obj.emails = ApiClient.convertToType(data['emails'], ['String']);
      if (data.hasOwnProperty('phone_numbers'))
        obj.phoneNumbers = ApiClient.convertToType(data['phone_numbers'], ['String']);
      if (data.hasOwnProperty('push_tokens'))
        obj.pushTokens = ApiClient.convertToType(data['push_tokens'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} emails
 */
ListIdMembersBody1.prototype.emails = undefined;

/**
 * @member {Array.<String>} phoneNumbers
 */
ListIdMembersBody1.prototype.phoneNumbers = undefined;

/**
 * @member {Array.<String>} pushTokens
 */
ListIdMembersBody1.prototype.pushTokens = undefined;

