/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2021.11.26
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The ListSubscribePostResponseDataInner model module.
 * @module model/ListSubscribePostResponseDataInner
 * @version 2021.11.26
 */
export class ListSubscribePostResponseDataInner {
  /**
   * Constructs a new <code>ListSubscribePostResponseDataInner</code>.
   * @alias module:model/ListSubscribePostResponseDataInner
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ListSubscribePostResponseDataInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListSubscribePostResponseDataInner} obj Optional instance to populate.
   * @return {module:model/ListSubscribePostResponseDataInner} The populated <code>ListSubscribePostResponseDataInner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListSubscribePostResponseDataInner();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('phone_number'))
        obj.phoneNumber = ApiClient.convertToType(data['phone_number'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
ListSubscribePostResponseDataInner.prototype.id = undefined;

/**
 * @member {String} email
 */
ListSubscribePostResponseDataInner.prototype.email = undefined;

/**
 * @member {String} phoneNumber
 */
ListSubscribePostResponseDataInner.prototype.phoneNumber = undefined;

