/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2021.11.26
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The ListIdMembersBody model module.
 * @module model/ListIdMembersBody
 * @version 2021.11.26
 */
export class ListIdMembersBody {
  /**
   * Constructs a new <code>ListIdMembersBody</code>.
   * The profiles that you would like to add to the list. Each object in the array must have an &#x60;email&#x60; or &#x60;phone_number&#x60;. You can also provide additional properties as key-value pairs.
   * @alias module:model/ListIdMembersBody
   * @class
   * @param profiles {Array.<Object.<String, Object>>} 
   */
  constructor(profiles) {
    this.profiles = profiles;
  }

  /**
   * Constructs a <code>ListIdMembersBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListIdMembersBody} obj Optional instance to populate.
   * @return {module:model/ListIdMembersBody} The populated <code>ListIdMembersBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListIdMembersBody();
      if (data.hasOwnProperty('profiles'))
        obj.profiles = ApiClient.convertToType(data['profiles'], [{'String': Object}]);
    }
    return obj;
  }
}

/**
 * @member {Array.<Object.<String, Object>>} profiles
 */
ListIdMembersBody.prototype.profiles = undefined;

