/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2021.11.26
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {ListSubscribePostResponseDataInner} from './ListSubscribePostResponseDataInner.js';

/**
 * The ListSubscribePostResponseData model module.
 * @module model/ListSubscribePostResponseData
 * @version 2021.11.26
 */
export class ListSubscribePostResponseData extends Array {
  /**
   * Constructs a new <code>ListSubscribePostResponseData</code>.
   * @alias module:model/ListSubscribePostResponseData
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>ListSubscribePostResponseData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListSubscribePostResponseData} obj Optional instance to populate.
   * @return {module:model/ListSubscribePostResponseData} The populated <code>ListSubscribePostResponseData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListSubscribePostResponseData();
      ApiClient.constructFromObject(data, obj, 'ListSubscribePostResponseDataInner');
    }
    return obj;
  }
}
// Implement OneOfinlineResponse2006 interface:
