/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2021.11.26
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The MetricExportData model module.
 * @module model/MetricExportData
 * @version 2021.11.26
 */
export class MetricExportData {
  /**
   * Constructs a new <code>MetricExportData</code>.
   * @alias module:model/MetricExportData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MetricExportData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MetricExportData} obj Optional instance to populate.
   * @return {module:model/MetricExportData} The populated <code>MetricExportData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MetricExportData();
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'String');
      if (data.hasOwnProperty('values'))
        obj.values = ApiClient.convertToType(data['values'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {String} _date
 */
MetricExportData.prototype._date = undefined;

/**
 * @member {Array.<Number>} values
 */
MetricExportData.prototype.values = undefined;

