/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2022.03.29
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {MetricExportData} from './MetricExportData.js';

/**
 * The MetricExportResults model module.
 * @module model/MetricExportResults
 * @version 2022.03.29
 */
export class MetricExportResults {
  /**
   * Constructs a new <code>MetricExportResults</code>.
   * @alias module:model/MetricExportResults
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MetricExportResults</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MetricExportResults} obj Optional instance to populate.
   * @return {module:model/MetricExportResults} The populated <code>MetricExportResults</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MetricExportResults();
      if (data.hasOwnProperty('segment'))
        obj.segment = ApiClient.convertToType(data['segment'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [MetricExportData]);
    }
    return obj;
  }
}

/**
 * @member {String} segment
 */
MetricExportResults.prototype.segment = undefined;

/**
 * @member {Array.<module:model/MetricExportData>} data
 */
MetricExportResults.prototype.data = undefined;

