/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2021.11.26
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The MetricTimelineEventProperties model module.
 * @module model/MetricTimelineEventProperties
 * @version 2021.11.26
 */
export class MetricTimelineEventProperties {
  /**
   * Constructs a new <code>MetricTimelineEventProperties</code>.
   * @alias module:model/MetricTimelineEventProperties
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MetricTimelineEventProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MetricTimelineEventProperties} obj Optional instance to populate.
   * @return {module:model/MetricTimelineEventProperties} The populated <code>MetricTimelineEventProperties</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MetricTimelineEventProperties();
      if (data.hasOwnProperty('$event_id'))
        obj.eventId = ApiClient.convertToType(data['$event_id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} eventId
 */
MetricTimelineEventProperties.prototype.eventId = undefined;

