/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2021.11.26
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The MetricIntegration model module.
 * @module model/MetricIntegration
 * @version 2021.11.26
 */
export class MetricIntegration {
  /**
   * Constructs a new <code>MetricIntegration</code>.
   * @alias module:model/MetricIntegration
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MetricIntegration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MetricIntegration} obj Optional instance to populate.
   * @return {module:model/MetricIntegration} The populated <code>MetricIntegration</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MetricIntegration();
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} _object
 */
MetricIntegration.prototype._object = undefined;

/**
 * @member {String} id
 */
MetricIntegration.prototype.id = undefined;

/**
 * @member {String} name
 */
MetricIntegration.prototype.name = undefined;

/**
 * @member {String} category
 */
MetricIntegration.prototype.category = undefined;

