/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2022.03.29
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The PrivacyEmail model module.
 * @module model/PrivacyEmail
 * @version 2022.03.29
 */
export class PrivacyEmail {
  /**
   * Constructs a new <code>PrivacyEmail</code>.
   * @alias module:model/PrivacyEmail
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PrivacyEmail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrivacyEmail} obj Optional instance to populate.
   * @return {module:model/PrivacyEmail} The populated <code>PrivacyEmail</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PrivacyEmail();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
PrivacyEmail.prototype.email = undefined;

