/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2021.11.26
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The TrackPayloadPost model module.
 * @module model/TrackPayloadPost
 * @version 2021.11.26
 */
export class TrackPayloadPost {
  /**
   * Constructs a new <code>TrackPayloadPost</code>.
   * @alias module:model/TrackPayloadPost
   * @class
   * @param data {String} 
   */
  constructor(data) {
    this.data = data;
  }

  /**
   * Constructs a <code>TrackPayloadPost</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrackPayloadPost} obj Optional instance to populate.
   * @return {module:model/TrackPayloadPost} The populated <code>TrackPayloadPost</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TrackPayloadPost();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} data
 * @default '{"token": "PUBLIC_KEY", "event": "Ordered Product", "customer_properties": {"$email": "abraham.lincoln@klaviyo.com"}, "properties": {"item_name": "Boots","$value": 100}}'
 */
TrackPayloadPost.prototype.data = '{"token": "PUBLIC_KEY", "event": "Ordered Product", "customer_properties": {"$email": "abraham.lincoln@klaviyo.com"}, "properties": {"item_name": "Boots","$value": 100}}';

