/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2022.03.29
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';
import {TrackPayloadCustomerProperties} from './TrackPayloadCustomerProperties.js';
import {TrackPayloadProperties} from './TrackPayloadProperties.js';

/**
 * The TrackPayload model module.
 * @module model/TrackPayload
 * @version 2022.03.29
 */
export class TrackPayload {
  /**
   * Constructs a new <code>TrackPayload</code>.
   * @alias module:model/TrackPayload
   * @class
   * @param token {String} 
   * @param customerProperties {module:model/TrackPayloadCustomerProperties} 
   * @param properties {module:model/TrackPayloadProperties} 
   */
  constructor(token, customerProperties, properties) {
    this.token = token;
    this.customerProperties = customerProperties;
    this.properties = properties;
  }

  /**
   * Constructs a <code>TrackPayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrackPayload} obj Optional instance to populate.
   * @return {module:model/TrackPayload} The populated <code>TrackPayload</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TrackPayload();
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
      if (data.hasOwnProperty('customer_properties'))
        obj.customerProperties = TrackPayloadCustomerProperties.constructFromObject(data['customer_properties']);
      if (data.hasOwnProperty('properties'))
        obj.properties = TrackPayloadProperties.constructFromObject(data['properties']);
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], Object);
    }
    return obj;
  }
}

/**
 * @member {String} token
 */
TrackPayload.prototype.token = undefined;

/**
 * @member {module:model/TrackPayloadCustomerProperties} customerProperties
 */
TrackPayload.prototype.customerProperties = undefined;

/**
 * @member {module:model/TrackPayloadProperties} properties
 */
TrackPayload.prototype.properties = undefined;

/**
 * @member {Object} time
 */
TrackPayload.prototype.time = undefined;

