/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2022.03.29
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The TrackPayloadProperties model module.
 * @module model/TrackPayloadProperties
 * @version 2022.03.29
 */
export class TrackPayloadProperties {
  /**
   * Constructs a new <code>TrackPayloadProperties</code>.
   * @alias module:model/TrackPayloadProperties
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TrackPayloadProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrackPayloadProperties} obj Optional instance to populate.
   * @return {module:model/TrackPayloadProperties} The populated <code>TrackPayloadProperties</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TrackPayloadProperties();
      if (data.hasOwnProperty('$event_id'))
        obj.eventId = ApiClient.convertToType(data['$event_id'], 'String');
      if (data.hasOwnProperty('$value'))
        obj.value = ApiClient.convertToType(data['$value'], 'String');
      if (data.hasOwnProperty('YOUR_CUSTOM_FIELD'))
        obj.YOUR_CUSTOM_FIELD = ApiClient.convertToType(data['YOUR_CUSTOM_FIELD'], Object);
    }
    return obj;
  }
}

/**
 * @member {String} eventId
 */
TrackPayloadProperties.prototype.eventId = undefined;

/**
 * @member {String} value
 */
TrackPayloadProperties.prototype.value = undefined;

/**
 * @member {Object} YOUR_CUSTOM_FIELD
 */
TrackPayloadProperties.prototype.YOUR_CUSTOM_FIELD = undefined;

