/*
 * Klaviyo API
 * Empowering creators to own their destiny
 *
 * OpenAPI spec version: 2022.03.29
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient.js';

/**
 * The V1EmailtemplatesBody model module.
 * @module model/V1EmailtemplatesBody
 * @version 2022.03.29
 */
export class V1EmailtemplatesBody {
  /**
   * Constructs a new <code>V1EmailtemplatesBody</code>.
   * @alias module:model/V1EmailtemplatesBody
   * @class
   * @param name {String} The name of the email template.
   * @param html {String} 
   */
  constructor(name, html) {
    this.name = name;
    this.html = html;
  }

  /**
   * Constructs a <code>V1EmailtemplatesBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1EmailtemplatesBody} obj Optional instance to populate.
   * @return {module:model/V1EmailtemplatesBody} The populated <code>V1EmailtemplatesBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1EmailtemplatesBody();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('html'))
        obj.html = ApiClient.convertToType(data['html'], 'String');
    }
    return obj;
  }
}

/**
 * The name of the email template.
 * @member {String} name
 * @default 'New Template Name'
 */
V1EmailtemplatesBody.prototype.name = 'New Template Name';

/**
 * @member {String} html
 * @default '<html><body><p>This is an email for {{ email }}.</p></body></html>'
 */
V1EmailtemplatesBody.prototype.html = '<html><body><p>This is an email for {{ email }}.</p></body></html>';

